### ISSUE TITLE
Extract information about the type of annotation

### ISSUE THREAD

**Issue by david-lennox** [coherentgraphics/cpdf-binaries#1]
G'day. Many thanks for this great tool. I have been using it to extract annotations from my pdf documents that I have marked up for my research. It would be very useful if the annotation output included some metadata about the annotation. In particular whether it was a highlight or text box and who was the author. Cheers.

**Comment by johnwhitington** [comment]
Forthcoming v2.3 has support for reading more data about annotations. This is the beginnings of a proper "annotations" file format (like the bookmarks file format) which will (eventually) allow roundtripping of annotations.

**Comment by johnwhitington** [comment]
Do you happen to have an example file I can look at?

**Comment by johseb** [comment]
Will the new "annotations" file format in v2.3 allow the round trip for links destination?
It would be great to export all destinations, batch change them and re-import.

And will cpdf extract all annotations or will user be able to filter based on kind?

Thanks.

**Comment by johnwhitington** [comment]
Yes, that's the idea. Though I'm afraid annotations work missed the deadline for v2.3 (which will be released in October), so you'll have to wait for v2.4.

**Comment by boomtow** [comment]
Ya that looks good

**Comment by johnwhitington** [comment]
Forthcoming v2.5 has support for exporting annotations in JSON format. More work will be required to allow round-tripping, but it will appear eventually.

Meanwhile, v2.5 will also have simple functions for search and replace on any key-value pair in the PDF. So, replace the /URI in a weblink annotation will be possible in v2.5, for example.

**Comment by johnwhitington** [comment]
Intriguing sentence in the PDF spec - does this mean deciding which objects are required for roundtripping annotations is a solved problem? To investigate:

"In addition, beginning in PDF 1.3, FDF can be used to define a container for annotations that are separate from the PDF document to which they apply."

**Comment by johseb** [comment]
Is the FDF format a text (human readable) file format or a binary one? I think the ability to easily filter/modify the exported annotations before (re)import into a PDF file is an important requirement.

**Comment by johnwhitington** [comment]
@johseb to be investigated. However, the key point is that it looks like the FDF format delineates exactly which objects are required for successful round-tripping of annotations, and how they are written back into the PDF file. So we can always just use the FDF guidelines/format but actually do it in JSON.

**Comment by johnwhitington** [comment]
v2.6 will come with annotation round-tripping.
