### ISSUE TITLE
New  feature: save pdf info 

### ISSUE THREAD

**Issue by wallace7souza** [coherentgraphics/cpdf-binaries#10]
Hi guys!
Is there a way to save pdf info?
In my scenario, i can't read console output, even passing ' > out.txt' i'm not able to save.
My ideia is to use something on CLI like this:
cpdf.exe -info my.pdf -o "c:/temp/info.txt"
Any help is welcome!

**Comment by johnwhitington** [comment]
What is preventing you from capturing the console output? If you're using cpdf via a script, there will be a method to capture the output, I'm sure.

**Comment by wallace7souza** [comment]
I'm developing a firefox addon, for some restrition, outputs from shell commands are not capturing otherwise using '> out.txt' but for some reason is not working =/

**Comment by wallace7souza** [comment]
I found a solution.
The right way to use and get output from process is this.

https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/system_child_process
