### ISSUE TITLE
Star/end of chunk padded

### ISSUE THREAD

**Issue by wallace7souza** [coherentgraphics/cpdf-binaries#11]
Hi all!
Is there a way to set start and end of chunck padded?
like: **cpdf -split a.pdf -chunk 10 -o out@S%%-@E%%.pdf**
Thanks!

**Comment by johnwhitington** [comment]
Not presently, but I'll consider this a feature request.

**Comment by johnwhitington** [comment]
Wish granted in forthcoming v2.3. Syntax is @S@@@ etc.
