### ISSUE TITLE
smaller filesize on multiple runs on the same file, bug?

### ISSUE THREAD

**Issue by necros2k7** [coherentgraphics/cpdf-binaries#12]
subj

**Comment by johnwhitington** [comment]
Please supply an example file, and the command line you used.

Thanks.

**Comment by necros2k7** [comment]
smpdf 1.pdf -o 2.pdf
smpdf 2.pdf -o 3.pdf
smpdf 3.pdf -o 4.pdf
smpdf 4.pdf -o 5.pdf
smpdf 5.pdf -o 6.pdf
smpdf 6.pdf -o 7.pdf
smpdf 7.pdf -o 8.pdf
[1.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/491420/1.pdf)

**Comment by johnwhitington** [comment]
```
feast:Downloads john$ smpdf 1.pdf -o 2.pdf
Initial file size is 350140 bytes
Beginning squeeze: 15 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 347861 bytes, 99.35% of original.
feast:Downloads john$ smpdf 2.pdf -o 3.pdf
Initial file size is 347861 bytes
Beginning squeeze: 15 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 347863 bytes, 100.00% of original.
feast:Downloads john$ smpdf 3.pdf -o 4.pdf
Initial file size is 347863 bytes
Beginning squeeze: 15 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 347858 bytes, 100.00% of original.
feast:Downloads john$ smpdf 4.pdf -o 5.pdf
Initial file size is 347858 bytes
Beginning squeeze: 15 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 347859 bytes, 100.00% of original.
feast:Downloads john$ smpdf 5.pdf -o 6.pdf
Initial file size is 347859 bytes
Beginning squeeze: 15 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 347861 bytes, 100.00% of original.
```

I can't replicate that here...

**Comment by necros2k7** [comment]
Ehmm...
feast:Downloads john$ smpdf 1.pdf -o 2.pdf
Initial file size is 350140 bytes
Beginning squeeze: 15 objects
Squeezing page data and xobjects
Recompressing document
Final file size is **347861** bytes, 99.35% of original.

feast:Downloads john$ smpdf 3.pdf -o 4.pdf
Initial file size is 347863 bytes
Beginning squeeze: 15 objects
Squeezing page data and xobjects
Recompressing document
Final file size is **347858** bytes, 100.00% of original.

**Comment by necros2k7** [comment]
why close if it`s still make files smaller on multiple runs? 8-)
