### ISSUE TITLE
Removal of smpdf

### ISSUE THREAD

**Issue by parnmatt** [coherentgraphics/cpdf-binaries#13]
Why was smpdf removed? I found that tool incredibly useful.

Not only did it reduce filesize a little, sometime it massively made a difference to filesize of combined PDFs.
My colleague had even created a PDF poster for a conference, which would display fine on macOS and linux; but not on Adobe Reader on Windows (which was what the Printing Company was using) …quickly ran through smpdf to reorganise the structure …absolutely find.

**Comment by johnwhitington** [comment]
It still exists - it is now `cpdf -squeeze` instead.

**Comment by parnmatt** [comment]
it is? Fantastic, thanks for your swift reply
