### ISSUE TITLE
Stamp replace images

### ISSUE THREAD

**Issue by Frolanta** [coherentgraphics/cpdf-binaries#15]
I’m using your tool to stamp multiple pdf into one big pdf at specific coordinates.
My issue is sometime there are images embedded on those files and is seems there is a problem with that. After the stamp all images (on the big pdf) are replaced with the image of the stamp.

Is guess that’s because they have the same name (Im0) and after the stamp there are renamed aIm0

`./cpdf -image-resolution 30000 out-12.pdf`
1, /aIm0, 498, 1033, 200.902220, 200.902220
1, /aIm0, 498, 1033, 200.902220, 200.902220
1, /aIm0, 498, 1033, 197.830693, 197.830693
1, /aIm0, 498, 1033, 85.698914, 244.084083
1, /aIm0, 498, 1033, 206.657406, 206.657406
1, /aIm0, 498, 1033, 204.113852, 204.113852
1, /aIm0, 498, 1033, 204.113852, 204.113852

There is an exemple:
Big file:
![before](https://cloud.githubusercontent.com/assets/6041477/24650394/549871d4-192a-11e7-8a40-0d0fe394857f.png)

Stamp:
![stamp](https://cloud.githubusercontent.com/assets/6041477/24650410/60b85d44-192a-11e7-88b4-dd6aa38375df.png)

Command:
`./cpdf -stamp-on rotated-fixed-11.pdf -relative-to-cropbox -pos-left "311.8110236219 680.3149606295999" out-11.pdf -o out-12.pdf`

Result:
![after](https://cloud.githubusercontent.com/assets/6041477/24650399/5aa61554-192a-11e7-8e1c-832c34e31fa2.png)
(The one that are not replaced do not use images)

This is what I get when inspecting the file with acrobat:
![screen shot 2017-04-04 at 11 08 09](https://cloud.githubusercontent.com/assets/6041477/24650451/8354b708-192a-11e7-91d8-d10f8c472976.png)

I can edit image(154) with photoshop and it confirm all the images have been replaced by the one on the stamp.

I’m using the OSX binary and all my pdf are version 1.5

Am I missing something or ?

files used:
[out-11.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/892623/out-11.pdf)
[rotated-fixed-11.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/892622/rotated-fixed-11.pdf)

**Comment by johnwhitington** [comment]
I think this should be fixable. But I will need to see the start of the process, where `cpdf` first gets involved. It looks like out-11.pdf has already been processed by `cpdf`.

Can you provide original files which have not been processed by `cpdf`, and exhibit a command, or series of commands, which leads to a file containing duplicate image names?

**Comment by Frolanta** [comment]
Yes you are right, there has been multiple stamps and rotations performed on out-11.pdf
Here a complete process with originals files.

```
./cpdf -rotate 270 1.pdf AND -upright -o rotated-0.pdf
./cpdf -stamp-on rotated-0.pdf -relative-to-cropbox -pos-left "992.1259842515 0" out-0.pdf -o out-1.pdf

./cpdf -rotate 270 2.pdf AND -upright -o rotated-1.pdf
./cpdf -stamp-on rotated-1.pdf -relative-to-cropbox -pos-left "566.929133858 0" out-1.pdf -o out-2.pdf
```

Files:
[1.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/895519/1.pdf)
[2.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/895520/2.pdf)
[out-0.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/895521/out-0.pdf)

**Comment by johnwhitington** [comment]
FIxed in trunk `camlpdf`.

https://github.com/johnwhitington/camlpdf/commit/83499533a4195fda9e61a8d05b35eaaa97331c51

**Comment by Frolanta** [comment]
Great, when do you think this will be available in cpdf ?

**Comment by johnwhitington** [comment]
You can compile it from source yourself, by picking the trunk versions of `camlpdf` and `cpdf`, or you can wait for the next release in a year or so.

Or, if you're a paying customer, we can provide a binary build straight away.

**Comment by Frolanta** [comment]
Working great, thanks.
