### ISSUE TITLE
Release tags for different cpdf versions?

### ISSUE THREAD

**Issue by sax** [coherentgraphics/cpdf-binaries#16]
First of all, thank you for providing these binaries here.

I just ran into an issue where our code started failing because we were using an older version of cpdf, and when pulling down the latest binaries from master our code was doing the wrong thing. It made me think that it would be helpful if you were to make a release tag when you were to update the current version of cpdf. That way, people could download the specific version they are targeting by name, without having to jump to a specific git hash.

Anyways, just a thought.

**Comment by johnwhitington** [comment]
Sounds like a good idea. The source is tagged.

What was the incompatibility you ran across?

**Comment by sax** [comment]
I didn't have much time to debug the actual problem, especially since jumping back to cpdf 2.1 reverted to the expected behavior. Also unfortunately, the content of the PDF is proprietary to a client and I'm unable to share it.

It seems to work on OS X, and fails on Linux in CircleCI. So it's possible there's another dependency that is causing the problem.

```
cpdf -merge /tmp/first.pdf /tmp/second.pdf AND -set-title "merged title" -o /tmp/merged-result.pdf
/home/ubuntu/.local/bin/cpdf: 2: /home/ubuntu/.local/bin/cpdf: Syntax error: "(" unexpected
```

**Comment by johnwhitington** [comment]
Hmm. Sounds like a shell problem of some sort. `cpdf` never generates the phrase "Syntax error".

By the way, have you checked that your client actually has a license for `cpdf`? If they are paying you for your work, then they are a commercial enterprise and need a license. Or you need one for being paid. In either case, you would then be using binaries directly from us, rather than the ones on Github.

**Comment by sax** [comment]
Yeah... except for the fact that when I drop in an older version of cpdf
the problem goes away.

I believe the client does have a license. I just grabbed the binary from
github since it's a different platform.
