### ISSUE TITLE
PDF corruption

### ISSUE THREAD

**Issue by CreeperLava** [coherentgraphics/cpdf-binaries#17]
Here is a rather serious bug I noticed when running "cpdf -squeeze" on a PDF :
![](http://i.imgur.com/fm4ZWRC.png)

A lot of the text vanished, but all pictures remain. The file size was only reduced from 80 Mo to 79 Mo, so I'm not sure what happened. I think the data is still there, since the file size hasn't changed much, but it's somehow hidden. I did try opening each PDF with different PDF viewers (Adobe and Foxit). Do note this PDF is the only one I noticed having this issue.

I can send you the file I used for testing if needed, just tell me where to send it.

**Comment by johnwhitington** [comment]
Yes, please send it. I don't think I can receive an email that large, so please upload it somewhere and send me the link.

Also, please give the exact command line you used.

**Comment by johnwhitington** [comment]
This file was produced by finereader, and it contains malformed content streams. The malformity is on the “Tz” operator. Here is an example extract:

96.-42 Tz

The “Tz” operator takes a single floating-point operand. “96.-42” is not a valid floating point number. Thus, PDF software can fail to parse the PDF.

The file in question was created in 2001, so it may already have been fixed.

I have filed a bug with the authors of finereader.

`cpdf` should complain about this rather than silently failing, though. So I'm going to fix that.

**Comment by johnwhitington** [comment]
I have altered cpdf to give a proper error message.

Leaving this bug open to consider whether we can find some way to repair these malformed streams, or to skip malformities. But this, in general, might be a fraught plan.

**Comment by CreeperLava** [comment]
Thank you very much ! To have cpdf detect that this can happen is enough for me. What I fear the most is when programs corrupt files without me noticing :).

**Comment by javiergutierrezchamorro** [comment]
Any chance to have update binaries?

**Comment by johnwhitington** [comment]
We can only provide updated binaries for commercial users with a support contract. So, you can either wait for the next release, or build it yourself from source.

**Comment by javiergutierrezchamorro** [comment]
Thanks @johnwhitington. Will wait for the next binary release then @CreeperLava.

**Comment by javiergutierrezchamorro** [comment]
Any news about the updated binaries?

**Comment by johnwhitington** [comment]
There won't be any until the next release, which will be next year.

**Comment by javiergutierrezchamorro** [comment]
Thanks.
And what about updating the source at the respository, so I can build it myself as you suggested?

**Comment by johnwhitington** [comment]
It has already been updated!

**Comment by javiergutierrezchamorro** [comment]
Thanks. Was looking at here, but found it on your repos. Just in case anyone is interested:
https://github.com/johnwhitington/cpdf-source
