### ISSUE TITLE
How to extract text from pdf using cpdf?

### ISSUE THREAD

**Issue by duoguo** [coherentgraphics/cpdf-binaries#19]
How to extract text from pdf using cpdf? like pdf to text or pdfhtml?

**Comment by johnwhitington** [comment]
We don't really have any facilities for text extraction -- since PDF is a visual format, it involves reconstruction.

There is a very simple text dumper -extract-text, but you shouldn't expect the output to be much use in reality.

**Comment by micsel** [comment]
One could use 'xpdf' which includes 'pdftotext.exe'

**Comment by ooker777** [comment]
How to use `-extract-text`? I try 
```
cpdf -extract-text in.pdf -o out.txt
```
And it only creates an empty file.

**Comment by johnwhitington** [comment]
See above comment "you shouldn't expect the output to be much use in reality". There's a reason it's undocumented...
