### ISSUE TITLE
Unable to set subject ( incl umlaut characters ) of PDF - even when forcing utf8

### ISSUE THREAD

**Issue by manuel-koch** [coherentgraphics/cpdf-binaries#2]
Trying to set subject of a PDF by invoking the following command :
`cpdf.exe -utf8 -control ctrl.txt in.pdf -o out.pdf`
using the following content of ctrl.txt ( incl a linebreak ) :
```
-set-subject "Multiline
Subject with \"quotes\" and umlauts öäüß"
```
Control file was edited/saved using utf8 encoding.

cpdf.exe prints the following error message :
>For non-commercial use only
>To purchase a license visit http://www.coherentpdf.com/
>
>cpdf encountered an error. Technical details follow:
>
>Bad page specification Multiline
>Subject with "quotes" and umlauts ├Â├ñ├╝├ƒ. Raw error was Cpdf.PageSpecBadSyntax. Last page was 1

cpdf sets subject properly when umlaut characters are not present in ctrl.txt.

**Comment by johnwhitington** [comment]
I move to closet this, unless OP can reproduce.
