### ISSUE TITLE
No option to disable auto center.

### ISSUE THREAD

**Issue by juliomgm** [coherentgraphics/cpdf-binaries#21]
Hi.
I tested the app so i could use -scale-to-fit, but i don't what the result to be centered, i what the result to be on top.

Is there a way to do this?
Thanks.

**Comment by johnwhitington** [comment]
You can use -shift to move content around a page, but of course you would have to calculate the coordinates yourself.

**Comment by johnwhitington** [comment]
If you can't get it working, please send an example file to me using the address john@ coherentgraphics.co.uk

**Comment by juliomgm** [comment]
The pdf file height and width is variable and not fixed. That is why i what to -scale-to-fit but without autocenter.

**Comment by johnwhitington** [comment]
Right. We'll keep this bug open as a feature request, then, unless you're a paying customer, in which case we could do it immediately.

**Comment by juliomgm** [comment]
Ok. Thanks.

**Comment by johnwhitington** [comment]
It is now possible, in the upcoming v2.7, to add `-top 0` `-left 0` `-bottom 0` or `right 0` to achieve this.
