### ISSUE TITLE
-range not working for adding text

### ISSUE THREAD

**Issue by Bern741** [coherentgraphics/cpdf-binaries#22]
Hi all

I'm simply trying to add text exclusively on page 2 with the following command:

`cpdf -range 2-2 -add-text "Signed on 12/04/2017" -topleft 400 -font "Helvetica" -font-size 10 in.pdf -o out.pdf`

However, it puts the text also on page 1. Am I doing something wrong or is this a bug?

Thanks

**Comment by johnwhitington** [comment]
Ranges, however they are specified, follow the input file on the command line, applying to the most recent input file specified.

So, write “in.pdf -range 2” or just “in.pdf 2”.

**Comment by Bern741** [comment]
Thanks for the quick answer. This solves the problem perfectly!
