### ISSUE TITLE
Combination of "add-text" and "stamp-on"

### ISSUE THREAD

**Issue by Bern741** [coherentgraphics/cpdf-binaries#23]
Hi all

Before I buy the product, I need to know this works. I try to insert text and an image in one go. Split in two separate commands, this works perfectly:

add-text:
`cpdf -add-text "Some sample text" -pos-left "100 200" -font "Helvetica" -font-size 10 in.pdf 2 -o out.pdf`

stamp-on:
`cpdf -stamp-on logo.pdf in.pdf 2 -o out.pdf -pos-left "-200 -100"`

However, if I combine those two commands with AND it puts the logo on a new third page. The text remains at its intended position. 

combination:
`./cpdf -add-text "Signed on 12/04/2017" -pos-left "100 200" -font "Helvetica" -font-size 10 in.pdf 2 AND range 2-2 stamp-on logo.pdf -pos-left "-200 -100" -o out.pdf`

Am I missing something here? I'd appreciate any help :-)

Cheers

**Comment by johnwhitington** [comment]
I don't see that your first two commands work: you write to `out.pdf` then read again from `in.pdf`.

You have a typo in the combined one, you need `-range` not just `range`.

`./cpdf -add-text "Signed on 12/04/2017" -pos-left "100 200" -font "Helvetica" -font-size 10 in.pdf 2 AND -range 2 stamp-on logo.pdf -pos-left "-200 -100" -o out.pdf`

Try that and let me know how you get on.

**Comment by Bern741** [comment]
You are right. I must have been blind! With your corrected command it works now. Thanks a lot for the fast support!

**Comment by johnwhitington** [comment]
Great!

Are you running these via a script? It's probably best to try individual commands out directly on the command line if you can -- you get much better error reports that way.
