### ISSUE TITLE
Bug: Combine retated over.pdf and under.pdf

### ISSUE THREAD

**Issue by zxdawn** [coherentgraphics/cpdf-binaries#25]
I have two PDF:
1. Watermark (note.pdf) : 19.5 * 26 inch
2. Document (page.pdf) : 10 * 7.5 inch

```
./cpdf -scale-to-fit "7.5in 10in" note.pdf AND -rotate 90 note.pdf -o note2.pdf
./cpdf -combine-pages note2.pdf page.pdf -o out.pdf
```
This has the same result as:
```
./cpdf -scale-to-fit "7.5in 10in" note.pdf -o note2.pdf
./cpdf -combine-pages note2.pdf page.pdf -o out.pdf
```
 
Here are pictures:
1. note.pdf:
![note.pdf](https://user-images.githubusercontent.com/30388627/35467213-c2581bf0-0346-11e8-8545-203cc4a2ec07.png)
2. page.pdf:
![page.pdf](https://user-images.githubusercontent.com/30388627/35467219-cec95cfa-0346-11e8-91c4-3f8adcc2f113.png)
3. out.pdf:
![out.pdf](https://user-images.githubusercontent.com/30388627/35467224-d708e764-0346-11e8-8f15-fe9ed70d919b.png)

**Comment by zxdawn** [comment]
The information of rotated and no_rotated pdf:

Rotated:

> Title:
> Subject:        unspecified
> Keywords:
> Author:         anonymous
> Creator:        ReportLab PDF Library - www.reportlab.com
> Producer:       ReportLab PDF Library - www.reportlab.com
> CreationDate:   Wed Jan 24 23:17:56 2018
> ModDate:        Wed Jan 24 23:17:56 2018
> Tagged:         no
> UserProperties: no
> Suspects:       no
> Form:           none
> JavaScript:     no
> Pages:          1
> Encrypted:      no
> Page size:      540 x 720 pts
> Page rot:       90
> File size:      10972 bytes
> Optimized:      no
> PDF version:    1.4

No_rotated:

> Title:
> Subject:        unspecified
> Keywords:
> Author:         anonymous
> Creator:        ReportLab PDF Library - www.reportlab.com
> Producer:       ReportLab PDF Library - www.reportlab.com
> CreationDate:   Wed Jan 24 23:17:56 2018
> ModDate:        Wed Jan 24 23:17:56 2018
> Tagged:         no
> UserProperties: no
> Suspects:       no
> Form:           none
> JavaScript:     no
> Pages:          1
> Encrypted:      no
> Page size:      540 x 720 pts
> Page rot:       0
> File size:      10971 bytes
> Optimized:      no
> PDF version:    1.4

You can see that 'Page size' is same.

**Comment by johnwhitington** [comment]
Please run -upright on the 90 degree instead of using -rotate.

Let me know how you get on...

**Comment by zxdawn** [comment]
I got the same wrong result when using -upright.

**Comment by johnwhitington** [comment]
Sorry, upright in addition to rotate. i used:

```
gorge:files john$ cpdf -scale-to-fit "7.5in 10in" note.pdf AND -rotate 90 AND -upright note.pdf -o note2.pdf
gorge:files john$ cpdf -combine-pages note2.pdf page.pdf -o out.pdf
```
[out.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/1670891/out.pdf)

**Comment by zxdawn** [comment]
Thank you for your help! It works!
