### ISSUE TITLE
Ranges break pdf with only one page

### ISSUE THREAD

**Issue by jonasdw** [coherentgraphics/cpdf-binaries#26]
When trying to add pagenumbers (starting from page 2) and the pdf is only one page long, an empty pdf is generated.

**Comment by johnwhitington** [comment]
Are you sure? What should happen is that an error is returned, because the page range is invalid for that PDF... No PDF output will be produced.

**Comment by jonasdw** [comment]
@johnwhitington I'll look into that right away!

**Comment by jonasdw** [comment]
@johnwhitington It seems that cpdf indeed throws a range error of some sort.
