### ISSUE TITLE
Please add option for `-merge` to add auto-generate bookmarks

### ISSUE THREAD

**Issue by agguser** [coherentgraphics/cpdf-binaries#32]
For example, `cpdf -merge -add-bookmarks i1.pdf i2.pdf -o o.pdf` would create o.pdf with two new bookmarks ("i1" and "i2", to their first pages in o.pdf) added (not replaced).

**Comment by johnwhitington** [comment]
Wish granted in forthcoming v2.3

**Comment by agguser** [comment]
The added bookmarks are not in UTF-8!

Run
```
% cpdf -merge-add-bookmarks 1-หนึ่ง.pdf 2-สอง.pdf -o all.pdf
```
, then open `all.pdf` and view its bookmarks!
