### ISSUE TITLE
Cannot edit/preview in GIMP after -squeeze

### ISSUE THREAD

**Issue by Peppernrino** [coherentgraphics/cpdf-binaries#35]
After running certain .pdf image files through `cpdf.exe -squeeze "C:\Users\******\Desktop\about.pdf" -o "C:\Users\******\temp\about.pdf"` , I get this error when trying to open the file in GIMP:

> Opening 'C:\Users\\******\Desktop\about.pdf' failed: Could not load 'C:\Users\\******\Desktop\about.pdf': PDF document is damaged

It opens fine in Foxit Reader with no visible corruption otherwise I would have added this to https://github.com/coherentgraphics/cpdf-binaries/issues/17, but will not open in Windows Photo Viewer.

**Comment by johnwhitington** [comment]
Please provide an example input file...

**Comment by johnwhitington** [comment]
I did this:

```
gorge:sq john$ cpdf -squeeze about.pdf -o squeezed.pdf
Initial file size is 1038 bytes
Beginning squeeze: 7 objects
Squeezing... Down to 6 objects
Squeezing page data and xobjects
Recompressing document
Final file size is 780 bytes, 75.14% of original.
```

And the result file loads in Adobe Acrobat, MacOs Preview, pdftk, qpdf and Ghostscript.

I don't have access to Windows Photo viewer. So I'm not sure how to progress this...

Odd that it fails in GIMP and Windows Photo Viewer though.

Could you try reporting it as a GIMP bug, and link the bug report here?

**Comment by Peppernrino** [comment]
Will do. :+1:
