### ISSUE TITLE
Feature Request: Please add an filter to the -draft option to select images by name for removal

### ISSUE THREAD

**Issue by cilahn** [coherentgraphics/cpdf-binaries#36]
Hello, i'd love to see an added feature to the -draft command. When testing a pdf with i.e.
cpdf -image-resolution 1280 kodex.pdf
1, /Im1, 1240, 1654, 149.963718, 150.018140
2, /Im2, 1276, 1689, 149.964742, 149.973362
3, /Im3, 1276, 1689, 149.964742, 149.973362
3, /Im4, 894, 236, 149.949681, 149.809564

it would be really helpfull if i.e. only '/Im4' could be select for removal. As noted by your support this could lead to someting similar like this:

<quote from support email>
We can imagine syntax like this:

cpdf -draft in.pdf 3 -draft-remove-only "/Im4” -o out.pdf

That wouldn’t take too long to implement.
</quote from support email>

Thank you for cpdf and friendly support,

Cilahn

**Comment by johnwhitington** [comment]
Wish granted in forthcoming v2.3
