### ISSUE TITLE
it's good tools,add page numbers,how can I set start number

### ISSUE THREAD

**Issue by blackleexu** [coherentgraphics/cpdf-binaries#39]

**Comment by johnwhitington** [comment]
To stamp numbers only on certain pages:

```
cpdf in.pdf 6-50 -add-text "%Page" -o out.pdf
```

To stamp numbers starting at a different number:

```
cpdf in.pdf -add-text "%Bates" -bates 20 -o out.pdf
```

**Comment by blackleexu** [comment]
@johnwhitington 
Thinks! It's worked for me.

**Comment by blackleexu** [comment]
@johnwhitington and another question，add page-num I need bottomright and diagonal style.My mother tongue is not English，sorry my poor English

**Comment by johnwhitington** [comment]
This combination is not possible in one command.

I suggest making a PDF file using -diagonal, then moving it using -shift, then combining with the original PDF using -stamp-on.
