### ISSUE TITLE
Not compatible with Win10

### ISSUE THREAD

**Issue by valuex** [coherentgraphics/cpdf-binaries#40]
I am using cpdf to extract serveral  pages from a large pdf , but it says cpdf is not compatible with my OS.   (I am using Chinese, so I can not copy & paste the orginal alert here).  
**cpdf:** v2.3 (tried 32-bit and 64-bit, both has the same error)  
**OS:** win10 pro, 1903,  64-bit

**Comment by johnwhitington** [comment]
This the error message you get if you try to run 32 bit software on a 64 bit windows or vice versa.

Can you check again?

When I tried it on my Windows 10 system, I  get:

```
John Whitington@DESKTOP-OJQME0H ~
$ wget https://github.com/coherentgraphics/cpdf-
Saving to: ‘cpdf.exe’

cpdf.exe                               100%[============================================================================>]   6.18M  1.10MB/s    in 4.8s

2019-10-06 17:42:15 (1.30 MB/s) - ‘cpdf.exe’ saved [6477513/6477513]


John Whitington@DESKTOP-OJQME0H ~
$ ./cpdf.exe
-bash: ./cpdf.exe: Permission denied

John Whitington@DESKTOP-OJQME0H ~
$ chmod +x cpdf.exe

John Whitington@DESKTOP-OJQME0H ~
$ ./cpdf.exe
For non-commercial use only
To purchase a license visit http://www.coherentpdf.com/
```
 
So perhaps I need to update the files to have the executable permission bit properly set?

**Comment by valuex** [comment]
> @valuex did this help?

Sorry for my late reply.   
The error message says that the binary in folder ** windows**  or ** windows32**  is the 16-bit one, not 64-bit or 32 bit one.   
Maybe the version uploaded is not the right version.  
Can you help to check it? Thanks a lot.
<img width="340" alt="1png" src="https://user-images.githubusercontent.com/3627812/66710210-69fc3080-eda6-11e9-9ec5-2db7c7773ecd.png">

**Comment by valuex** [comment]
Sorry for bothering.  
Previously, I just right click the **cpdf.exe** in the folder windows.  Then an error message says not compatible. But today, I download the entire project as a zip file and un-zip it. No more un-compatible error. Kind of wired. 
Thanks.
