### ISSUE TITLE
CPDF on macOS Catalina

### ISSUE THREAD

**Issue by peavine** [coherentgraphics/cpdf-binaries#41]
Cpdf does not appear to run on macOS Catalina and instead gives the following error message:

“cpdf” cannot be opened because the developer cannot be verified.

This happens both when cpdf is run from a terminal window and within an Applescript. Adding cpdf to allowed apps in Security & Privacy did not change this.

Will a version be released that is compatible with Catalina or am I doing something wrong. Thanks.

**Comment by peavine** [comment]
I had so much trouble with Catalina--both hardware and software--that I went back to Mojave for now. Thanks.

**Comment by johnwhitington** [comment]
Yes, there will be a new version provided. But not until the author can upgrade to Catalina without problems with other essential software...

**Comment by johnwhitington** [comment]
I have just installed a VM with catalina, and downloaded the binary. Here is the procedure:

1. Try to run cpdf executable from the terminal: a whinge box appears. Click 'cancel'.
2. Open System Preferences --> Security and Privacy --> General
3. Cpdf is listed as being banned. Click "Allow Anyway".

This process allows me to run cpdf ok on catalina (release version).

My understanding is that Apple will actually enforce the new, more draconian, policy from January 2020. I will make sure we're ready for that by providing a new executable.

I am reopening this issue for visibility.

**Comment by peavine** [comment]
Thanks for the information. I'm back on Mojave now but would like to give Catalina another try after a few maintenance releases. It's good to know that cpdf will work.
