### ISSUE TITLE
Does the non-commercial licence permit government use?

### ISSUE THREAD

**Issue by splintax** [coherentgraphics/cpdf-binaries#42]
Hi there – thanks for releasing this software, and especially the documentation. The licence gives "teaching, academic research and personal experimentation" as examples of authorised use, and describes unauthorised commercial purposes as, for example, "running business operations ... using the Software in the creation or use of commercial products or any other activity whose purpose is to procure a commercial gain to you or others."

Could you please clarify whether it is intended that use of `cpdf` for government purposes would be covered by the non-commercial licence, assuming that the tool is used for typical government activities which are not intended to procure and do not result in "a commercial gain"?

**Comment by johnwhitington** [comment]
Yes, for government use (except government-funded education or research) you would indeed need a license.
