### ISSUE TITLE
ARMv7 binary

### ISSUE THREAD

**Issue by miguelzf** [coherentgraphics/cpdf-binaries#5]
Hi
Can you make a binary for ARMv7? I've tried to build cpdf and camlpdf, but run into some trouble. I'm not familir with the Caml dev system
Thanks for any help

**Comment by johnwhitington** [comment]
Do you have the OCaml compiler installed?

With just a C compiler and "make" you should be able to build the OCaml bytecode system at least. Let me know when you have OCaml installed on your ARM system, and I can show you how to compile camlpdf and cpdf. It should be simple.

**Comment by miguelzf** [comment]
Ok thanks for the help.
I'm first trying to build it on amd64, debian. I've installed the compiler, libs, packages, opam, and a bunch of other stuff.
I have installed the camlpdf package thru opam, the installer says it finished fine. 
But ocamlfind still cannot find the package, this is the log:

ocamlfind ocamldep -native cpdfcommand.mli > ._ncdi/cpdfcommand.di
ocamlfind ocamldep -native cpdf.mli > ._ncdi/cpdf.di
ocamlfind ocamldep -native cpdfstrftime.mli > ._ncdi/cpdfstrftime.di
ocamlfind ocamldep -native xmlm.mli > ._ncdi/xmlm.di
ocamlfind ocamldep cpdfcommandrun.ml > ._d/cpdfcommandrun.d
ocamlfind ocamldep cpdfcommand.ml > ._d/cpdfcommand.d
ocamlfind ocamldep cpdf.ml > ._d/cpdf.d
ocamlfind ocamldep cpdfstrftime.ml > ._d/cpdfstrftime.d
ocamlfind ocamldep xmlm.ml > ._d/xmlm.d
ocamlfind ocamlc -package camlpdf -c -annot xmlm.mli
ocamlfind: Package `camlpdf' not found
OCamlMakefile:1056: recipe for target 'xmlm.cmi' failed

**Comment by miguelzf** [comment]
I have also managed to build camlpdf myself, but don't know how to use the package to build cpdf. 
And i tried now to install cpdf with opam, the package is there and apparently opam installs it fine, but still it seems it doesn't include a simple binary tool.

**Comment by johnwhitington** [comment]
To build yourself, it it sufficient to run "make" and "make install" for camlpdf. OCamlfind will then know where to find camlpdf to build cpdf. Just "make" in cpdf should produce the cpdf executable.

Are you sure you're using OPAM correctly? See here about opam init / opam config env:

https://opam.ocaml.org/doc/FAQ.html#Whydoesopaminitneedtoaddstufftomyinitscriptswhyisevalopamconfigenvneeded

**Comment by miguelzf** [comment]
Ah, that was precisely the issue! I had done opam init earlier, must have missed something.

Now i get this:
ocamlfind ocamlopt -package camlpdf -c -annot -g cpdf.ml
File "cpdf.ml", line 292, characters 12-37:
Error: This function has type
         string option -> string option -> Pdfio.input -> Pdf.t
       It is applied to too many arguments; maybe you forgot a `;'.
OCamlMakefile:1076: recipe for target 'cpdf.cmx' failed

**Comment by johnwhitington** [comment]
When you got the source, did you get a tagged released version from github, or trunk?

Both CamlPDF and CPDF must have the same version number (the latest for both is v2.1.1).

**Comment by miguelzf** [comment]
cpdf from the repo, camlpdf from opam. Possible mismatch yeah..

I was now trying on ARM, the opam version (from apt-get, ubuntu 14) there is 1.1.1, which apparently is not recent enough:
"[ERROR] Your version of OPAM (1.1.1) is not recent enough to read ~/.opam/repo/default/packages/tcpip/tcpip.2.2.1/opam. Upgrade OPAM to a more recent version (at least 1.2) to read this file correctly."

I guess i'll have to build both cpdf and calmpdf from source on ARM. That's another thing i didn't understand: after building camlpdf, i get the libs, but how can i pass them, or some kind of package, to ocamlfind to build cpdf?

**Comment by miguelzf** [comment]
nvm about that, got it! Thanks a lot for the help :)
