### ISSUE TITLE
How to add-text with chinese fonts ?

### ISSUE THREAD

**Issue by ekoz** [coherentgraphics/cpdf-binaries#50]
command is 
```
cpdf -pos-center "154 624" -add-text "Mr Chang" in.pdf -o out.pdf
```
the out.pdf file is created, and the text is added.
but when I change "Mr Chang" to "张三"，it is blank

**Comment by johnwhitington** [comment]
Cpdf uses the Standard 14 PostScript fonts which are Latin script only. Cpdf does not know how to embed arbitrary fonts from your computer into the PDF.

It is unlikely, given the size of chinese character sets that you will be able to embed such a font yourself, and selecting characters from it using codepoints is likely to require lots of technical knowledge.

So, the best option is to create a PDF with just the text, using whatever program you can (on the command line, maybe XeTeX?). You can then use -combine-pages or -stamp-on in cpdf to make the final result.

**Comment by ekoz** [comment]
@johnwhitington thanks for your reply, I will have a try.
