### ISSUE TITLE
cpdf crashes on Mac OS X 10.7.5 (Lion)

### ISSUE THREAD

**Issue by RobK88** [coherentgraphics/cpdf-binaries#52]
I am unable to run cpdf on Mac OS X Lion (10.7.5)

grinch$ ./cpdf 
Illegal instruction: 4

I am able to run cpdfsqueeeze just fine on my Mac running Lion.  It is just cpdf that crashes on Lion.

**Comment by johnwhitington** [comment]
The current version of cpdf will not run on Lion. If you contact me using the form on coherentpdf.com , so I have your email address, I can give you access to older versions of cpdf which will run.

**Comment by RobK88** [comment]
Thanks for the quick reply.  

You may want to consider updating your website at https://community.coherentpdf.com/. The website states that cpdf is compatible with Mac OS X 10.6 and above.  That is true but it sounds like one needs to ask for special access to the legacy binaries which are compatible with the older versions of Mac OS X.

**Comment by RobK88** [comment]
I just used the contact form at coherentpdf.com and sent you my EMAIL address.  When you get a chance, please send me the links to the legacy versions of cpdf.  Thanks!

**Comment by johnwhitington** [comment]
Done. Thanks
