### ISSUE TITLE
Limite use memory?

### ISSUE THREAD

**Issue by igortice** [coherentgraphics/cpdf-binaries#56]
Is it possible to limit the CPDF memory usage in the merge action? I have a problem here that certain files end up not being merged and the merge process remains undefined on the server, which causes the use of memory to the limit of the machine, which brings down the server.

**Comment by johnwhitington** [comment]
Sorry I missed this. Do you mean that the process goes on forever, never completing the merge? If so, I'd be interested to see example files.

Your operating system should have a mechanism for killing processes, but you don't say what OS you're using.
