### ISSUE TITLE
Add/Edit/Delete Bookmark in an existing PDF

### ISSUE THREAD

**Issue by soubhikchatterjee** [coherentgraphics/cpdf-binaries#59]
Is it possible to Add/Edit/Delete Bookmark in an existing PDF and save those changes in the pdf file?

**Comment by johnwhitington** [comment]
Yes, absolutely. You can use the commands from Chapter 6 of the manual. First `-list-bookmarks` or `list-bookmarks-json`, then edit as appropriate, then use `-add-bookmarks` or `-add-bookmarks-json` with your edited list.
