### ISSUE TITLE
Removing embedded pdfs from pdf

### ISSUE THREAD

**Issue by Anjali05** [coherentgraphics/cpdf-binaries#62]
Hi,

Is there a way I can remove embedded pdfs(which I use for images) from the main PDF file? I tried -remove-files but it does not seem to work.

Thanks

**Comment by johnwhitington** [comment]
Can you send an example file? If it's sensitive, you can send it to john at coherentgraphics dot co dot uk instead of uploading it here.

**Comment by Anjali05** [comment]
@johnwhitington I do not need this anymore. Thanks.
