### ISSUE TITLE
OS X 12.4 (Monterey) claims that this is malware

### ISSUE THREAD

**Issue by shearerp** [coherentgraphics/cpdf-binaries#66]
Tried to use the ARM version to merge two PDFs and got this message:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/93137416/179317909-34d97252-6125-4045-839d-15011097fc7f.png">

It's probably a false positive but I hope there's a way to run this that doesn't have my Mac screaming that it's malware.

**Comment by johnwhitington** [comment]
Thanks for reporting.

Cpdf is codesigned but not notarized. I will have to take another look at notarization.

You can go to Settings —> security to allow the executable.

The message does seem rather apocalyptic. Is this standard Macos, or do you have some third-party virus scanner installed? “Will damage” rather than “may damage” doesn’t really sound like Apple’s style!

**Comment by shearerp** [comment]
No third party stuff to my knowledge. Pretty sure it is a Mac OS warning.

I was a little shocked too, but over the years there's been a slow creep of more aggressive warnings and restrictions on "unofficial" apps.

**Comment by johnwhitington** [comment]
Ok, I think I know how to fox this. I will update this bug tomorrow.

**Comment by johnwhitington** [comment]
Does System preferences —> Security & Privacy —> General —> Open Anyway work?

**Comment by shearerp** [comment]
I know what you're talking about but it doesn't appear in this version of OS X. After attempting to run cpdf at the command line and opening System Preferences, this is all I see:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/93137416/179321830-8fe70bf9-4ca3-44c5-b8b2-5636ec14a9b5.png">

**Comment by johnwhitington** [comment]
One last possible workaround: have you tried downloading and running the Intel version under rosetta?

**Comment by shearerp** [comment]
I was looking into this utility to help a friend but she ended up using
something else. So, no need for workarounds for now. Getting pulled AFK,
thanks for looking into it!

**Comment by johnwhitington** [comment]
Ok, fixed. You can re-download the ZIP to get the new binaries.

(The fix was to re-codesign them. Not sure why.)

**Comment by shearerp** [comment]
That did it! I can now do the "open anyway" trick. Thanks!

**Comment by johnwhitington** [comment]
That's a relief. Thanks for the report.
