### ISSUE TITLE
How to perform a Cut and Stack N-Up?

### ISSUE THREAD

**Issue by maxiride** [coherentgraphics/cpdf-binaries#68]
The Cut and Stack N-Up is the process of imposing an input pdf file so that the resulting PDF is an N-Up of the input but the pages are arranged in such a manner that they can be cut and stacked to obtain the original order.

An image is worth a thousand words in this case.

![AH2XIBqP+G0eAAAAAElFTkSuQmCC](https://user-images.githubusercontent.com/3630857/196046655-34554c3d-18cc-4c0d-8b20-d98d5c6265ba.png)

**Comment by johnwhitington** [comment]
Get the number of pages:

```
cpdf -pages cpdfmanual.pdf
96
```

Divide by four, and split:

```
cpdf -split cpdfmanual.pdf -chunk 24 -o chunk%%%.pdf
```

Now merge in collation mode:

```
cpdf -merge chunk*.pdf -collate -o collated.pdf
```

Now impose 2x2:

```
cpdf -impose-xy "2 2" collated.pdf -o out.pdf
```

I have only briefly tested this - but if it's not the right answer, it's close to it.

**Comment by maxiride** [comment]
Thanks for the quick response!

The steps seem to exactly obtain the desired result, now that I understand how to do it with cpdf I think the steps can be reproduced for any given rows and columns too.

I'll tinker a bit for the output paper size and margins between the "logical" sheets.


However, if I were to print in duplex the even numbered sheets (which would be the backside) will need to have the sequence mirrored in order for the correct back to be printed on the rear of it's front. I guess I can get how to rearrange the pages for this result but I gladly accept suggestions.

Even in this case a picture is worth more :)

![IMG_20221016_204316](https://user-images.githubusercontent.com/3630857/196052441-985952d3-e702-4fa9-bd4b-bb6c8a6ba947.jpg)

**Comment by johnwhitington** [comment]
`-rtl` is the answer, but you won't be able to do it in one impose operation. You'll have to split the file back up into chunks before imposing half of them with `-rtl` and half of them without, and then merge the results.
