### ISSUE TITLE
stamp logo from a non PDF source (for instance PNG)

### ISSUE THREAD

**Issue by maxiride** [coherentgraphics/cpdf-binaries#69]
I've tried to play around the CLI today, and while I did solve the #68 (thanks for the tips @johnwhitington) I understand that the cpdf CLI only accepts PDFs as input files for logos and watermarks.

Is there any workaround or is this an intended limitation for reasons I miss to see?

**Comment by johnwhitington** [comment]
No, cpdf only manipulates PDF files. You could use another command line tool - imagemagick, for example, to convert your PNG to a PDF.
