### ISSUE TITLE
-scale-contents incorrectly handles link boxes

### ISSUE THREAD

**Issue by JimJarvis** [coherentgraphics/cpdf-binaries#7]
After applying -scale-contents option, the original link boxes are not scaled accordingly. As you can see in the screenshot below, the boxes are floating in their original positions: 

![image](https://cloud.githubusercontent.com/assets/3018029/12486474/e54c9b6e-c030-11e5-854b-a5ca956ab611.png)

Thanks!

**Comment by johnwhitington** [comment]
See Bug 29 in cpdf-source
