### ISSUE TITLE
Refused On Mac

### ISSUE THREAD

**Issue by wangliang1989** [coherentgraphics/cpdf-binaries#70]
I am on Mac 12.6 ARM
The computer refused to run cpdf, and cannot find the "Allow anyway" button anymore in the System Preferences --> Security & Privacy --> General.
Below is the screenshots. Although I am using Chinese language, I think you will agree there is no "Allow anyway" button anymore.

![823CBD1A8E8F6E0024F107AA3CBC9225](https://user-images.githubusercontent.com/12059719/198959862-f34938e5-0e9d-462c-a63c-f8c094cf1ca7.jpg)

![368116A506C20BB43C8ED9545251A4BC](https://user-images.githubusercontent.com/12059719/198959882-d52a11bf-845d-491f-92d6-003cb9a53faf.jpg)

**Comment by johnwhitington** [comment]
Works for me, in latest MacOS Ventura the option is still there, so it has not been removed:

![Untitled](https://user-images.githubusercontent.com/1702581/198996222-2451ab4f-509a-4cb9-9970-0e09e79ec6c0.jpg)

The process was this:

1) I downloaded and ran cpdf. It refused, bringing up a dialog box, and killing the cpdf process
2) I clicked "allow anyway" in settings
3) It failed running cpdf again, but allowed me to click "Ok" on the dialog box
4) Now it succeeds.

Can you try again?

(I have seen it suggested online that the system can be turned off with `sudo spctl --master-disable` but try it without doing that first.)

**Comment by wangliang1989** [comment]
I update the system today, and after the step 1 you show, I cannot find the "allow anyway"  button.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/12059719/199221877-b881202a-ab9c-4163-bdbe-7100563edda4.png">

**Comment by johnwhitington** [comment]
Very strange. The latest apple guidelines say it should work:

https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

Can you try also the "open" trick mentioned in this link?

If that doesn't work, I think you will have to do `sudo spctl --master-disable`.

**Comment by johnwhitington** [comment]
After typing `sudo spctl --master-disable`, you then need to go back into System Settings, and you should find a new option "anywhere" or similar has appeared. After you choose that, the executable should run:

<img width="409" alt="Untitled" src="https://user-images.githubusercontent.com/1702581/200803087-5c837fb2-4c4c-4ac9-a670-13a7ac77dff9.png">

**Comment by wangliang1989** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/12059719/200854327-145c2168-d64e-44dc-8da1-cf645cfc1f58.png">
 Although it is written in Chinese, I think you can understand.

**Comment by johnwhitington** [comment]
Did you try clicking ok on the dialog box and then running cpdf again?

**Comment by wangliang1989** [comment]
click cancel?

**Comment by johnwhitington** [comment]
No, you click on Ok. It probably kills cpdf, but then you run cpdf again, and it should work...

**Comment by wangliang1989** [comment]
But there is no "OK" button. The blue arrow is "remove to trash". the green arrow is "cancel".
<img width="617" alt="image" src="https://user-images.githubusercontent.com/12059719/201459216-a7343657-cfb4-485d-91a1-6d2a444ac880.png">

**Comment by johnwhitington** [comment]
Thanks. It is possible that MacOs has "quarantined" this executable - i.e marked it permanently. Can you try deleting it and re-downloading the .zip?

**Comment by wangliang1989** [comment]
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/12059719/201607234-b651564e-cb0d-4740-ba09-ea4d049cc325.png">

**Comment by johnwhitington** [comment]
It looks like you downloaded "cpdf-binaries-2.5.1" instead of "cpdf-binaries-master". The codesigning has changed:

<img width="836" alt="Untitled" src="https://user-images.githubusercontent.com/1702581/201647544-edc29991-c6b4-4b38-bb30-3ced6de4f523.png">

Change to "master" and click download again.

**Comment by wangliang1989** [comment]
Download from this link https://github.com/coherentgraphics/cpdf-binaries/raw/master/OSX-ARM/cpdf
can fix this issue
