### ISSUE TITLE
Version for Win XP

### ISSUE THREAD

**Issue by Dimsok** [coherentgraphics/cpdf-binaries#72]
I did try the last version on Windows XP. No error, but nothing happens. In description i have found that "The last version of cpdf compatible with Windows XP is v2.2.1." I did try to find that version, but unsuccessfull. If someone have binary v2.2.1, please upload it.

**Comment by johnwhitington** [comment]
Please contact me directly at john at coherentgraphics dot co dot uk and I will supply 2.2.1.

**Comment by Dimsok** [comment]
I have sent message on coherent mail. Still have not recieved the answer.

**Comment by johnwhitington** [comment]
Can't find anything here. Perhaps it ended up in the Junk. Can you give me your email address?

**Comment by Dimsok** [comment]
sokolov123d@gmail.com
Thanks.

**Comment by johnwhitington** [comment]
Email sent.

**Comment by Dimsok** [comment]
Thanks, got it.
