### ISSUE TITLE
How to check if the Windows installer runs properly?

### ISSUE THREAD

**Issue by ooker777** [coherentgraphics/cpdf-binaries#73]
I run the 64-bit installer, and it only flashes a cmd window before it disappears. I suspect Windows Security blocks it, but turning of the real-time doesn't make any difference. I don't see any new path registered in the path environmental variable, or any `cdpf` folder in appdata, localappdata, or programfiles.

**Comment by johnwhitington** [comment]
There is no installer; it's just a plain executable!

To install, simply copy cpdf.exe to your chosen location...

**Comment by ooker777** [comment]
Thanks, I forgot that. Just go into the terminal and cd to the location to call it
