### ISSUE TITLE
cpdf on macos Ventura

### ISSUE THREAD

**Issue by vosslab** [coherentgraphics/cpdf-binaries#75]
cannot run cpdf despite many tries, only gives the option:

"“cpdf” will damage your computer. You should move it to the Trash."

anyone else find a solution

**Comment by johnwhitington** [comment]
On what operating system?

**Comment by johnwhitington** [comment]
Did you follow these instructions from the README?

'MacOS: The executable is codesigned, but not notarized. If it refuses to run the first time, go to System Preferences --> Security & Privacy --> General and click "Allow anyway".'

**Comment by vosslab** [comment]
That does not appear to be an option in Ventura

**Comment by johnwhitington** [comment]
I get this:

![Untitled](https://user-images.githubusercontent.com/1702581/216781980-86a7a52a-9aa9-4a56-85c6-5094f8ff5470.jpg)

So I go to preferences and click on Open Anyway:

![Untitled 2](https://user-images.githubusercontent.com/1702581/216781987-13c63b96-47e0-4e77-8770-bae97bd30b59.jpg)

Then I get this:

![Untitled 3](https://user-images.githubusercontent.com/1702581/216781999-7e596b28-8892-466d-9fd3-cf0f38e46af7.jpg)

I click Ok, and type in my admin password. Then I can run cpdf:

![Untitled 4](https://user-images.githubusercontent.com/1702581/216782008-bc650895-bd01-48b6-b6aa-c7aa6396d55d.jpg)

**Comment by johnwhitington** [comment]
Perhaps the README should link to a webpage showing these screenshots. I'll note that for the next release.

**Comment by johnwhitington** [comment]
Oh, you might need to also choose "App Store and Identified developers" too - that's why you might be seeing different messages from me - note I didn't see anything about "move it to trash".

**Comment by vosslab** [comment]
Are using macos Ventura 13.1. I had cpdf working on the previous versions of macos.

1. wget -c 'https://github.com/coherentgraphics/cpdf-binaries/archive/refs/tags/v2.5.1.zip'
2. unzip v2.5.1.zip 
3. cd cpdf-binaries-2.5.1/OSX-ARM/
4. ./cpdf
<img width="479" alt="Screenshot 2023-02-04 at 12 04 01 PM" src="https://user-images.githubusercontent.com/3803992/216782645-8673c005-4bc6-464b-9cc3-81865dd7b241.png">
<img width="339" alt="Screenshot 2023-02-04 at 12 03 48 PM" src="https://user
<img width="223" alt="Screenshot 2023-02-04 at 12 04 23 PM" src="https://user-images.githubusercontent.com/3803992/216782664-7388bbf5-d343-4295-8b1f-6d6b9472ba92.png">
-images.githubusercontent.com/3803992/216782646-787c3050-73ef-410c-b8fd-1c975493e839.png">

**Comment by vosslab** [comment]
<img width="339" alt="Screenshot 2023-02-04 at 12 03 48 PM" src="https://user-images.githubusercontent.com/3803992/216782710-f8d28d5f-2f84-4a0f-b9ce-846fc9224b9b.png">

**Comment by johnwhitington** [comment]
Please see my previous suggestion to download master, not v2.5.1...

**Comment by vosslab** [comment]
Sorry, about the master part. That worked! Thanks!

1. wget -c 'https://github.com/coherentgraphics/cpdf-binaries/raw/master/OSX-ARM/cpdf'
2. chmod 755 cpdf
3. ./cpdf
4. pop saying cannot check
5. System Preferences --> Security & Privacy --> General and click "Allow anyway".'
6. ./cpdf 
7. works

**Comment by vosslab** [comment]
I should just compile from source

**Comment by johnwhitington** [comment]
Great! Glad it's working.
