### ISSUE TITLE
Can cpdf crop most pages while ignoring some?

### ISSUE THREAD

**Issue by Shohreh** [coherentgraphics/cpdf-binaries#77]
Hello,

Before trying to turn it into an EPUB, I need to crop the bottom of all pages, and the top of most pages of a PDF while ignoring the first page of each chapter.

Can cpdf do this?

Thank you.

PS: What's the difference between mediabox, cropbox, bleedbox, trimbox, and artbox?
![image](https://github.com/coherentgraphics/cpdf-binaries/assets/1541861/4d8f63ea-a8ad-4a42-af6c-76fdbbc8598f)

**Comment by johnwhitington** [comment]
Yes, you can use page ranges.

For example `cpdf in.pdf 1-6,8-13,15-19 -crop .......`.

I'm not sure what your EPUB conversion software will do with this cropping information, though.

You can find some info on boxes here:

https://www.prepressure.com/pdf/basics/page-boxes
