### ISSUE TITLE
window 10 64bit

### ISSUE THREAD

**Issue by jamacoe** [coherentgraphics/cpdf-binaries#78]
Windows 10 claims that the cpdf.exe provided in the x64 directory is 16-bit and that it can't be executed.

**Comment by johnwhitington** [comment]
Can you show me a screenshot?

**Comment by jamacoe** [comment]
Screenshot: 
![image](https://github.com/coherentgraphics/cpdf-binaries/assets/5889355/5fedfff7-f21d-422d-b93f-a15ecae33d7c)
I even tried all compatibility modes down to XP SP3.

However, I found a working cpdf.exe here: [](https://github.com/coherentgraphics/cpdf-binaries/archive/master.zip)
