### ISSUE TITLE
Concatenation of commands on a single input

### ISSUE THREAD

**Issue by DesBw** [coherentgraphics/cpdf-binaries#79]
So far as I understand, the way to write pdf metadata to a file is as follows: 

`cpdf -set-title "The greatestBook" file.pdf AND -set-author "The Greatest Author" file.pdf AND -set—keywords "mykeyword" file.pdf AND set-create "D:19970915110347-08’00’" file.pdf -o newFile.pdf`

The file name needs to be repeated after each command. That is redundant. It would be better if multiple  commands can applied to a single input: 

`cpdf —set-title "The  greatest Book" AND -set-author "The Greatest Author" AND -set—keywords "mykeyword" AND set-create "D:19970915110347-08’00’" file.pdf -o newFile.pdf`

**Comment by johnwhitington** [comment]
The correct syntax is to put the input file before the first AND:

`cpdf in.pdf -set-title "The greatest book" AND ..... AND ..... AND ..... -o out.pdf`

**Comment by johnwhitington** [comment]
No, that should work too. If it doesn't, please send me the full command line and an example input file.
