### ISSUE TITLE
Detect Spot Colors

### ISSUE THREAD

**Issue by nikjell** [coherentgraphics/cpdf-binaries#8]
Hi John,

would it be possible to add a function to detect the name of spot colours used in a PDF. I use cpdf heavily to check for lowres images in supplied PDFs but spot colours cause me a problem also. In Acrobat spot colour names are shown in the output preview window and If you import a PDF into InDesign the spot colours are added to your swatches palette.  I would really appreciate if you could look into adding a function to cpdf that could return a list of separations/spot colour names.

Many Thanks,
Nik

**Comment by johnwhitington** [comment]
Fixed in v2.2
