### ISSUE TITLE
Win 10 32bit versions (and those with lighter win7 devices)

### ISSUE THREAD

**Issue by GitHubRulesOK** [coherentgraphics/cpdf-binaries#82]
I use older poppler because there is no newer 32bit binaries and xpdf is 2022-04
the same with MuPDF June 2022 there seems to be a trend to leave 32bit users behind in the darker ages.

so last version of cpdf I can advise others to try is Version 2.5 (patchlevel 1, 31st Jan 2022) that's the insecure watermarked http://www.coherentpdf.com/ version

coincidentally my poppler 32bit is frozen at 22-02 so for continuous utility enhancements this past 18 months I have to look to PDFCPU (August 2023 for the present!)

It would be nice to be able to recommend a https://2.61x32 variant.

**Comment by johnwhitington** [comment]
What do you view as insecure about 2.5.1? Just that it's old, or something else?

I can still build 32 bit versions, just about, but the Windows 10 minimum comes from the OCaml toolchain - so an older version of OCaml would be needed to build it.

Let me have a look to see if I can still build a 32 bit version which runs on Windows 7.

**Comment by GitHubRulesOK** [comment]
sorry comment about insecure was inbuilt use of redirections to http rather than https

**Comment by johnwhitington** [comment]
Good catch. I've changed the message to https for the next version.

Meanwhile, please try this 32 bit build and let me know if it runs ok on Windows 7:

https://www.coherentpdf.com/tmp/17thOct2023.zip

**Comment by GitHubRulesOK** [comment]
Well it triggered a MS defender virus scan as an unknown but was left alone but seems to start off well enough, with a much bigger ? list of options :-)

```
17thOct2023\cpdf.exe -help
Syntax: cpdf [<operation>] <input files> [-o <output file>]

This is a copyrighted, commercial program, and may NOT be freely copied.

Version 2.6 (patch 1, 7th September 2023)

To buy, visit http://www.coherentpdf.com/

Input names are distinguished by containing a '.' and may be
followed by a page range specification, for instance "1,2,3"
or "1-6,9-end" or "even" or "odd" or "reverse".

Operations (See manual for full details):

  -version                            Print the cpdf version number
```

**Comment by johnwhitington** [comment]
Ok, thanks. I'll prepare a version to upload to the non-commercial binaries repository when I have time.

**Comment by GitHubRulesOK** [comment]
testing 32bit 7 takes longer as need to stoke the boiler first. will report here when full steam

**Comment by GitHubRulesOK** [comment]
Ok interesting difference works well enough on 32bit netbook (Win 7 Pro) but normal screen buffer is well exceeded by number of help lines especially unless  change 600 pixel number of command line buffer, still I should have used |more filter :-)

**Comment by GitHubRulesOK** [comment]
hmmm that actually threw me the convention is to use `cpdf -help|more` but cpdf uses channel 2 for output so |more dues not work you need to run `cpdf -help 2>help.txt` then `type help.txt|more`

**Comment by johnwhitington** [comment]
Ok, you can now find cpdf 2.6.1 for win32 in the cpdf-binaries repository:

https://github.com/coherentgraphics/cpdf-binaries
