### ISSUE TITLE
Create a PDF from two images

### ISSUE THREAD

**Issue by 2bllk** [coherentgraphics/cpdf-binaries#84]
I am trying to replace 2 pages at the beginning of a PDF file `document.pdf` with two images `1.jpg` and `2.jpg` following each other.
The commands I have tried using are:

```bash
cpdf -jpeg 1.jpg AND -jpeg 2.jpg AND document.pdf 3-end -o out.pdf
cpdf -merge -jpeg 1.jpg -jpeg 2.jpg document.pdf 3-end -o out.pdf
cpdf -jpeg 1.jpg -jpeg 2.jpg document.pdf 3-end -o out.pdf
```

They all create a file `out.pdf` where the first two pages are image `2.jpg` instead of pages `1.jpg` and `2.jpg`.

The commands below also create a PDF file `out.pdf` where both pages are `2.jpg`:

```bash
cpdf -jpeg 1.jpg AND -jpeg 2.jpg -o out.pdf
cpdf -merge -jpeg 1.jpg AND -jpeg 2.jpg -o out.pdf
```

Isn't there some kind of error in the program?

**Comment by johnwhitington** [comment]
I just tried

`cpdf -jpeg ~/Desktop/1.jpg AND -jpeg ~/Desktop/2.jpg AND cpdfmanual.pdf 3-end -o out.pdf`

and got the attached output PDF file, which looks right. Can you give the output of `cpdf -version` and, if possible, supply the two JPEGs and the document?

[out.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/13800828/out.pdf)

**Comment by 2bllk** [comment]
Of cource

The output of `cpdf -version`: `cpdf Version 2.6 (patch 1, 7th September 2023)`

The command I used:
```bash
cpdf.exe -jpeg a.jpg AND -jpeg b.jpg AND document.pdf 3-end -o out.pdf
```

Input and output files:

a.jpg
![a](https://github.com/coherentgraphics/cpdf-binaries/assets/45295926/3095d895-83db-4916-a2c2-11f18665c729)

b.jpg
![b](https://github.com/coherentgraphics/cpdf-binaries/assets/45295926/0e1eb4d0-0c2c-44da-a26e-fc6ab2aa1e38)

[document.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/13800837/document.pdf)
[out.pdf](https://github.com/coherentgraphics/cpdf-binaries/files/13800838/out.pdf)

**Comment by johnwhitington** [comment]
Ok, this appears to have already been fixed in trunk. If you let me know your platform, I can send you a binary of the current trunk.

**Comment by 2bllk** [comment]
Thank you, my platform is Windows64bit

**Comment by johnwhitington** [comment]
Please try https://www.coherentpdf.com/tmp/2ndJan2024.zip

**Comment by 2bllk** [comment]
Thx! It works fine
