### ISSUE TITLE
Add to Homebrew Cask

### ISSUE THREAD

**Issue by GeQi** [coherentgraphics/cpdf-binaries#86]
Is it possible to publish cpdf to the package manager Homebrew as a cask? It does not ask for a free license. [See](https://docs.brew.sh/Adding-Software-to-Homebrew#casks)

**Comment by johnwhitington** [comment]
Looking at the list of possible rejection criteria, we see:

`program is both open-source and CLI-only (i.e. it only uses the binary artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link to the issue from your pull request so we can see the discussion and reasoning for rejection).`

So it looks like it would have to be a built-from-source formula. I'll take a look for the next release.

**Comment by johnwhitington** [comment]
Just a note to check if the fact that cpdf is now AGPL alters anything wrt brew.

**Comment by johnwhitington** [comment]
Packinging is planned for several places (linux, brew, windows). So this doesn't need to be open to track any more.
