### ISSUE TITLE
Resize Page and Centre

### ISSUE THREAD

**Issue by flywire** [coherentgraphics/cpdf-binaries#88]
Page sizes can vary when scanning. How can a page size be resized with the original content centred at the original scale?

For example, Brother scanners deduct an unscannable margin from the page size, and if you are lucky it is the same on every page so it can be restored to a4portrait as follows:

```
	stream
	q
	578.16 0 0 824.40 0 0 cm
	/Im19 Do
...
	/MediaBox [0 0 578.16 824.40]
```

to

```
	stream
	q
	595 0 0 842 8.42 8.80 cm
	/Im19 Do
...
	/MediaBox [0 0 595    842   ]
```

> You can do this by using -mediabox or -crop, and then using -shift to move the content.
>
> Now, of course, that involves calculating the numbers to give to -shift yourself.

Manual calculations are inconvenient, and especially unworkable when page sizes vary by small amounts.

**Comment by flywire** [comment]
Preferably it should support https://en.wikipedia.org//wiki/Paper_size series setting with rotation being detected. For example, something close to letter of foolscap could be forced to A series, or A4 could be specified.

**Comment by johnwhitington** [comment]
Have just added -stretch in v2.7.2 to complement -scale-to-fit. So I suppose we could have -center-to-fit.

**Comment by johnwhitington** [comment]
Wish granted in upcoming v2.7.3.
