### ISSUE TITLE
Introduce a built-in feature to uniformly scale all pages within a PDF document to a user-specified page size

### ISSUE THREAD

**Issue by cassiuscai** [coherentgraphics/cpdf-binaries#89]
It would be great to have a built-in option in your PDF scaling tool that combines the `--scale-page` and `--scale-to-fit` options with automatic calculation of the scale ratio based on the PDF's width and height. This new feature could be invoked using the following command:

```bash
cpdf --scale-page-to-fit x_pts y_pts input.pdf -o out.pdf
```

Below is a Fish shell script I've created that performs the same task; however, it relies on multiple dependencies, which can be cumbersome. I utilize this script to scale or adjust the zoom level of my PDF files, ensuring they perfectly fit the dimensions of my iPad's screen and eliminating any unsightly black borders.

```fish
# pdf-scale is a function with definition
# Defined in /Users/casc/.config/fish/functions/pdf-scale.fish @ line 1
function pdf-scale
  if test (count $argv) -gt 2
    set -f inputfile $argv[3]
    # Get pdf file origin size
    set -l dx (pdf-width  $inputfile | sed 's/^[ \t]*//')
    set -l dy (pdf-height $inputfile | sed 's/^[ \t]*//')

    # Calc scale ratio
    set -l tx (echo $argv[1] | sed 's/^[ \t]*//')
    set -l ty (echo $argv[2] | sed 's/^[ \t]*//')

    set -l sx (math $tx / $dx)
    set -l sy (math $ty / $dy)

    # Set output file and convert
    set -f outfile (echo $argv[1]x$argv[2] - (basename $inputfile .pdf).pdf)
    if test (count $argv) -gt 3
      set -f outfile $argv[4]
    end

    show-line '-'
    echo Origin Page Size\t \| $dx \tx\t $dy pts
    echo Scaled Page Size\t \| $tx \t\tx\t $ty pts
    echo Scaled Page Ratio\t \| $sx \tx\t $sy
    echo Scaled Output File\t \| $outfile

    set -f scalePageFile (echo $TMPDIR/'scale-page'-$inputfile)

    begin
      cpdf -scale-page "$sx $sy" $inputfile -o $scalePageFile
      cpdf -scale-to-fit "$argv[1] $argv[2]" $scalePageFile -o $outfile
      rm -rf $scalePageFile
    end &> /dev/null
    show-result "Scale File" $outfile
  else
    echo "Usage: pdf-scale <width_in_pts> <height_in_pts> <input.pdf> [output.pdf]"
  end
end
```

**Comment by johnwhitington** [comment]
Can you explain more about what this does? The existing `-scale-to-fit` does "automatic calculation of the scale ratio based on the PDF's width and height" so I'm not sure what is different here... Can you give an example?

**Comment by cassiuscai** [comment]
#### I'm demonstrating the significant variations in PDF content manipulation approaches using a square image as an example.


1. **Original PDF**: The initial document has dimensions of 672x672 pixels, as shown below:


<img width="336" alt="origin.pdf" src="https://github.com/coherentgraphics/cpdf-binaries/assets/2277724/1950f71a-4c58-4148-b0a5-e970d220a631">

2. **Scaling Issue**: Using the command `cpdf --scale-to-fit '820 1180'` led to unintended results. The content was resized to fit within an 820x1180 bounding box; however, this introduced additional blank spaces above and below the original image, which was not the desired outcome:

<img width="336" alt="scala-to-fit.png" src="https://github.com/coherentgraphics/cpdf-binaries/assets/2277724/1250bb2f-9e3b-44e3-ae18-ebcdaabcd216">

3. **Custom Script Improvement**: Implementing a custom script yielded a more favorable result. The script independently scales the image's width and height before resizing it to the final page size, effectively avoiding any unnecessary whitespace:
<img width="336" alt="scale and then fit page size" src="https://github.com/coherentgraphics/cpdf-binaries/assets/2277724/2b77bd91-ad0c-4d17-b3c5-9996bb9033d5">

**Comment by johnwhitington** [comment]
Got it. Thanks.

**Comment by strauhmanis** [comment]
Attached is an example of terminology used in Affinity Publisher. Perhaps this may be helpful:


![Affinity Publisher Screenshot](https://github.com/coherentgraphics/cpdf-binaries/assets/17160191/c363f7c9-b230-4690-85e9-82d6c13667c5)

**Comment by johnwhitington** [comment]
Wish granted, with -stretch in upcoming v2.7.2.
