### ISSUE TITLE
Generate pdf from interval of pages

### ISSUE THREAD

**Issue by wallace7souza** [coherentgraphics/cpdf-binaries#9]
Hi all!
I need to split a pdf but i have a interval  of pages.
Example: cpdf.exe -split file.pdf start=10 end=20
Or something like this

**Comment by wallace7souza** [comment]
Sorry guys 
I thought it was using split parameter, but this command solved well
cpdf in.pdf 1-3,12-end -o out.pdf

**Comment by johnwhitington** [comment]
Glad you got it working!
