### ISSUE TITLE
Rebuilt with support for the Hardened Runtime

### ISSUE THREAD

**Issue by MichMich** [coherentgraphics/cpdf-binaries#94]
I've built a small Swift UI app for my sister that allows her to easily add her stationary design to any pdf. She's not very tech savvy, so this drag and drop tool is much easier for her. 

It works wonders, but unfortunately I'm unable to build and archive the app with the cpdf binary inside. It gives me the following error:

> "cpdf" must be rebuilt with support for the Hardened Runtime. Enable the Hardened Runtime capability in the project editor, test your app, rebuild your archive, and upload again.

Is there a way to rebuilt this binary with support for the hardened runtime?

Thanks!

**Comment by MichMich** [comment]
It looks like residing the binary solved the issue:

```bash
codesign --force --timestamp --options=runtime -s "Developer ID Application: Organisation Name (ORGANISTIONID)" -v /path/to/cpdf
```

Thanks for your great work!

**Comment by johnwhitington** [comment]
Great. Thanks for the update.
